name: hyl_ry_github_action_test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  front-end-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          cd ruoyi-ui
          npm install
          npm run build:prod
      - name: Remove old dist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: rm -rf /usr/share/wys-manage-ui
      - name: Upload dist
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "ruoyi-ui/dist/*"
          target: "/www/server/front_end"
          strip_components: 2

  back-end-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          mvn clean package
      - name: Upload dist
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "ruoyi-admin/target/ruoyi-admin.jar"
          target: "/www/server/back_end/jars"
          strip_components: 2
      - name: Rename jar file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mv -f /root/jars/ruoyi-admin.jar /root/jars/wys-manage.jar

  serve:
    runs-on: ubuntu-latest
    needs: [front-end-ci, back-end-ci]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload Nginx config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "bin/config/nginx.conf"
          target: "/etc/nginx/"
          strip_components: 2
      - name: Upload service Nginx config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "bin/config/wys.manage.nginx.http.conf"
          target: "/etc/nginx/conf.d/"
          strip_components: 2
      - name: Upload Systemd config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "bin/config/wys-manage.service"
          target: "/usr/lib/systemd/system/"
          strip_components: 2
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl daemon-reload
            systemctl stop hyl-ry.service
            systemctl start hyl-ry.service
            systemctl stop nginx.service
            systemctl start nginx.service
