name: CD

on:
  push:
    branches: [ master ]

jobs:
  front-end-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setpu node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          cd ui
          npm ci
          npm run build:prod
      - name: Upload dist
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "ruoyi-ui/dist/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.REMOTE_UI_TARGET }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}

  back-end-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload jar
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "ruoyi-admin/target/ruoyi-admin.jar"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.REMOTE_JAR_TARGET }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}

  serve:
    runs-on: ubuntu-latest
    needs: [front-end-deploy, back-end-deploy]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Upload back-end systemd config
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "config/systemd/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.REMOTE_SYSTEMD_CONF_TARGET }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      - name: Upload nginx config
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "config/nginx/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.REMOTE_NGINX_CONF_TARGET }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      - name: Enable namegeneratorsystem systemd service
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            systemctl daemon-reload
            systemctl enable ruoyi
            systemctl restart ruoyi
      - name: Restart nginx
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            systemctl restart nginx
